# Server Port
server:
  port: 8080

# Data Source props
spring:
  application:
    name: scorz-admin-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CSVData
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          default_schema: ${schema_name:public}
          jdbc:
            lob:
              non_contextual_creation: true
